- include_tasks: tasks/utils/wait_k8s.yaml

- name: Create fluxcd namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: flux-system
  register: _fluxcd_namespace

- name: Create SOPS secret
  no_log: true
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: sops-gpg
        namespace: flux-system
      stringData:
        sops.asc: "{{ lookup('pipe', 'echo ' + addons.fluxcd.sops + ' | base64 -d | gunzip') }}"
  when: addons.fluxcd.sops | default('') != ""
  register: _sops_secret

- name: Install FluxCD
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
    GITHUB_TOKEN: "{{ addons.fluxcd.token }}"
  ansible.builtin.command: >
    flux bootstrap github --personal
      --owner={{ addons.fluxcd.username }} --repository={{ addons.fluxcd.repository }}
      --branch={{ addons.fluxcd.branch | default('main') }} --path={{ addons.fluxcd.path | default('clusters/main') }}
  when: _fluxcd_namespace.changed or addons.fluxcd.update | default(false)
  register: _output
  until: _output.rc == 0
