- include_tasks: utils/wait_talos.yaml

- name: Check if node has been initialized
  ansible.builtin.command: |
    talosctl get machinestatus {{ talos_args }} --insecure
  register: node_status
  until: node_status.rc == 0 or node_status.stderr.find("certificate required") != -1
  changed_when: false
  failed_when: false
  retries: 25
  delay: 5

- name: Configure machine patches
  ansible.builtin.copy:
    content: "{{ patch | to_nice_yaml(2,false) }}"
    dest: "{{ datastore }}/patches/{{ inventory_hostname }}.yaml"
  when: patch | default({}) | length > 0

- name: Apply config
  ansible.builtin.command: >
    talosctl apply {{ talos_args }} --file="{{ datastore }}/configs/{{ node_type }}.yaml"
      --config-patch="{{ "@" + datastore + "/patches/" + inventory_hostname + ".yaml" if patch | default({}) | length > 0 }}"
      --insecure={{ true if node_status.rc == 0 else false }}
  register: _output
  until: _output.rc == 0
  retries: 25
  delay: 5
