name: talos-dev

services:
  talos-dev:
    image: ghcr.io/chickeniq/talos-manager:latest
    container_name: talos-dev
    network_mode: host
    stdin_open: true
    tty: true
    build: ./src
    # command: debug
    volumes:
      - ./dev.yaml:/host/config.yaml:ro
      - ~/.talos:/host/.talos
      - ~/.kube:/host/.kube
      # - ./data:/data/
