- include_tasks: tasks/utils/wait_k8s.yaml

- name: Get kubeconfig
  ansible.builtin.command: talosctl kubeconfig {{ talos_args }} {{ datastore }}/configs/kubeconfig --merge=false --force --force-context-name {{ cluster_name }}
  register: _output
  until: _output.rc == 0

- name: Check if host kubeconfig exists
  ansible.builtin.stat:
    path: "{{ kubeconfig_host }}"
  register: _kubeconfig_host

- name: Copy kubeconfig
  ansible.builtin.copy:
    src: "{{ kubeconfig }}"
    dest: "{{ kubeconfig_host }}"
  when: _kubeconfig_host.stat.exists == false

- name: Backup kubeconfig
  ansible.builtin.copy:
    src: "{{ kubeconfig_host }}"
    dest: "{{ kubeconfig_host }}.bak"
  when: _kubeconfig_host.stat.exists

- name: Merge kubeconfig
  ansible.builtin.command: talosctl kubeconfig {{ talos_args }} {{ kubeconfig_host }} --force --force-context-name {{ cluster_name }}
  register: _output
  until: _output.rc == 0
  when: _kubeconfig_host.stat.exists
