- include_tasks: utils/wait_k8s.yaml

- name: Create flux-system namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: flux-system
  register: _fluxcd_namespace

- name: Create SOPS secret
  no_log: true
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: sops-gpg
        namespace: flux-system
      stringData:
        sops.asc: "{{ lookup('pipe', 'echo ' + fluxcd.sops + ' | base64 -d | gunzip') }}"
  when: fluxcd.sops | default('') != ""

- name: Install FluxCD
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
    GITHUB_TOKEN: "{{ fluxcd.token }}"
  ansible.builtin.command: |
    flux bootstrap github --personal \
      --owner={{ fluxcd.user }} --repository={{ fluxcd.repo }} \
      --branch={{ fluxcd.branch }} --path={{ fluxcd.path }}
  when: _fluxcd_namespace.changed
  register: _output
  until: _output.rc == 0
  retries: 5
  delay: 5
